/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package joguinho.mover.bloco;

import javax.swing.JOptionPane;

/**
 *
 * @author laboratorio
 */
public class JFrame_JoguinhoPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrame_JoguinhoPrincipal.class.getName());

    /**
     * Creates new form JFrame_JoguinhoPrincipal
     */
    public JFrame_JoguinhoPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ghost1 = new javax.swing.JButton();
        btn_ghost2 = new javax.swing.JButton();
        btn_frutinha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_ghost1.setForeground(new java.awt.Color(153, 0, 255));
        btn_ghost1.setText("👻");
        btn_ghost1.setFocusable(false);

        btn_ghost2.setBackground(new java.awt.Color(255, 0, 51));
        btn_ghost2.setForeground(new java.awt.Color(255, 255, 255));
        btn_ghost2.setText("👻");
        btn_ghost2.setFocusable(false);

        btn_frutinha.setBackground(new java.awt.Color(153, 0, 255));
        btn_frutinha.setForeground(new java.awt.Color(255, 255, 255));
        btn_frutinha.setText("🍇");
        btn_frutinha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_frutinhaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btn_ghost1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(btn_ghost2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btn_frutinha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ghost2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ghost1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addComponent(btn_frutinha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_frutinhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_frutinhaKeyPressed
        int tecla = evt.getKeyCode();

    switch (tecla) {
        // Setas para GHOST1
        case 38: // CIMA
            new Thread() {
                @Override
                public void run() {
                    System.out.println("Indo para cima");
                    Movimenta.cima(btn_ghost1);
                }
            }.start();
            break;

        case 40: // BAIXO
            new Thread() {
                @Override
                public void run() {
                    System.out.println("Indo para baixo");
                    Movimenta.baixo(btn_ghost1, JFrame_JoguinhoPrincipal.this);
                }
            }.start();
            break;

        case 37: // ESQUERDA
            new Thread() {
                @Override
                public void run() {
                    System.out.println("Indo para esquerda");
                    Movimenta.esquerda(btn_ghost1);
                }
            }.start();
            break;

        case 39: // DIREITA
            new Thread() {
                @Override
                public void run() {
                    System.out.println("Indo para direita");
                    Movimenta.direita(btn_ghost1, JFrame_JoguinhoPrincipal.this);
                }
            }.start();
            break;

        // Teclas W A S D para GHOST2
        case 87: // W - CIMA
            new Thread() {
                @Override
                public void run() {
                    System.out.println("Indo para cima");
                    Movimenta.cima(btn_ghost2);
                }
            }.start();
            break;

        case 83: // S - BAIXO
            new Thread() {
                @Override
                public void run() {
                    System.out.println("Indo para baixo");
                    Movimenta.baixo(btn_ghost2, JFrame_JoguinhoPrincipal.this);
                }
            }.start();
            break;

        case 65: // A - ESQUERDA
            new Thread() {
                @Override
                public void run() {
                    System.out.println("Indo para esquerda");
                    Movimenta.esquerda(btn_ghost2);
                }
            }.start();
            break;

        case 68: // D - DIREITA
            new Thread() {
                @Override
                public void run() {
                    System.out.println("Indo para direita");
                    Movimenta.direita(btn_ghost2, JFrame_JoguinhoPrincipal.this);
                }
            }.start();
            break;

        default:
            // Tecla não tratada, não faz nada
            break;
    }

    // Verifica se houve colisão entre ghost1 e frutinha
    if (btn_ghost1.getBounds().intersects(btn_frutinha.getBounds())) {
        Movimenta.sorteiaPosicao(btn_frutinha, JFrame_JoguinhoPrincipal.this);
    }

    // Verifica se houve colisão entre ghost2 e frutinha
    if (btn_ghost2.getBounds().intersects(btn_frutinha.getBounds())) {
        Movimenta.sorteiaPosicao(btn_frutinha, JFrame_JoguinhoPrincipal.this);
    }
    }//GEN-LAST:event_btn_frutinhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrame_JoguinhoPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_frutinha;
    private javax.swing.JButton btn_ghost1;
    private javax.swing.JButton btn_ghost2;
    // End of variables declaration//GEN-END:variables
}
