
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author laboratorio
 */
public class JFrameServidor extends javax.swing.JFrame {

    /**
     * Creates new form JFrameServidor
     */
    public JFrameServidor() {
        initComponents();
        btnFecharServidor.setEnabled(false);
        jTextFieldTextoMensagem.setEnabled(false);
        jTextAreaMensagensRecebidas.setVisible(false);
//        jPanelCamposMensagens.setVisible(false);
    }

        static ServerSocket socketServidor;
        static Socket socketCliente;
        static ObjectOutputStream saida;
        static ObjectInputStream entrada;
        static LocalDateTime dataHora;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldApelido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPorta = new javax.swing.JTextField();
        jButtonIniciar = new javax.swing.JButton();
        jPanelCamposMensagens = new javax.swing.JPanel();
        jTextFieldTextoMensagem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMensagensRecebidas = new javax.swing.JTextArea();
        btnFecharServidor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Apelido:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Porta autorizada:");

        jTextFieldPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPortaActionPerformed(evt);
            }
        });

        jButtonIniciar.setBackground(new java.awt.Color(0, 204, 0));
        jButtonIniciar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonIniciar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jTextFieldTextoMensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTextoMensagemKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("CHAT");

        javax.swing.GroupLayout jPanelCamposMensagensLayout = new javax.swing.GroupLayout(jPanelCamposMensagens);
        jPanelCamposMensagens.setLayout(jPanelCamposMensagensLayout);
        jPanelCamposMensagensLayout.setHorizontalGroup(
            jPanelCamposMensagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldTextoMensagem)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCamposMensagensLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(62, 62, 62))
        );
        jPanelCamposMensagensLayout.setVerticalGroup(
            jPanelCamposMensagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCamposMensagensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldTextoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        jTextAreaMensagensRecebidas.setEditable(false);
        jTextAreaMensagensRecebidas.setColumns(20);
        jTextAreaMensagensRecebidas.setRows(5);
        jTextAreaMensagensRecebidas.setEnabled(false);
        jScrollPane1.setViewportView(jTextAreaMensagensRecebidas);

        btnFecharServidor.setBackground(new java.awt.Color(204, 0, 51));
        btnFecharServidor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFecharServidor.setForeground(new java.awt.Color(255, 255, 255));
        btnFecharServidor.setText("Encerrar conexão");
        btnFecharServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharServidorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Texto para enviar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFecharServidor))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelCamposMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonIniciar)
                    .addComponent(btnFecharServidor))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCamposMensagens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPortaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPortaActionPerformed

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        // TODO add your handling code here:
        if (jTextFieldApelido.getText().equals("") || jTextFieldPorta.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campos incompletos para conexão");
        } else {
            try {
                System.out.println("Servidor Iniciado!");
                socketServidor = new ServerSocket(Integer.parseInt(jTextFieldPorta.getText())); //CONSTRUTOR DO SERVERSOCKT RECEBE A PORTA DE TRABALHO
                //INSTANCIAR EM SEGUNDO O LEITOR
                socketCliente = socketServidor.accept(); //ACAO BLOQUEANTE QUE O SERVIDOR SÓ LIBERA QUANDO UM CLIENTE FIZER CONEXÃO                
                JOptionPane.showMessageDialog(this, "Servidor em funcionamento");
                
                try {
                    
                    new Thread() {
                        public void run() {
                            String fraseDoCliente;
                            btnFecharServidor.setEnabled(true);
                            jTextFieldTextoMensagem.setEnabled(true);
                            jTextAreaMensagensRecebidas.setVisible(true);
                            try {
                                saida = new ObjectOutputStream(socketCliente.getOutputStream()); //INSTANCIAR PRIMEIRO O ESCRITOR
                                entrada = new ObjectInputStream(socketCliente.getInputStream()); 
                                //ENQUANTO O CLIENTE ENVIAR TEXTO, EXIBIR NA TELA
                                while ((fraseDoCliente = (String) entrada.readObject()) != null) {
                                    dataHora = LocalDateTime.now();
                                    jTextAreaMensagensRecebidas.append(fraseDoCliente + " " + dataHora + "\n");
                                }
                            } catch (IOException ex) {
                                Logger.getLogger(JFrameServidor.class.getName()).log(Level.SEVERE, null, ex);
                            } catch (ClassNotFoundException ex) {
                                Logger.getLogger(JFrameServidor.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }.start();
                    saida.close();
                    entrada.close();
                    socketCliente.close();
                    socketServidor.close();
                    System.exit(0);
                } catch (IOException ex) {
                    Logger.getLogger(JFrameServidor.class.getName()).log(Level.SEVERE, null, ex);
                } 
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Exceção capturada ao ouvir/ler a porta " + jTextFieldPorta.getText() + " ou ao tentar conectar");
                //System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jTextFieldTextoMensagemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTextoMensagemKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String fraseDoServidor;
            
            fraseDoServidor = jTextFieldTextoMensagem.getText();
            try {
                saida.flush();
                saida.writeObject((jTextFieldApelido.getText() + ": " + fraseDoServidor));
                jTextFieldTextoMensagem.setText("");
            } catch (IOException ex) {
                Logger.getLogger(JFrameServidor.class.getName()).log(Level.SEVERE, null, ex);
            }            
        }
    }//GEN-LAST:event_jTextFieldTextoMensagemKeyPressed

    private void btnFecharServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharServidorActionPerformed
                    
        try {
            saida.close();                 
            entrada.close();                  
            socketCliente.close();                   
            socketServidor.close();                    
            JOptionPane.showMessageDialog(this, "Servidor encerrado.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao encerrar o servidor. ");
        }
              
    }//GEN-LAST:event_btnFecharServidorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameServidor().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFecharServidor;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelCamposMensagens;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMensagensRecebidas;
    private javax.swing.JTextField jTextFieldApelido;
    private javax.swing.JTextField jTextFieldPorta;
    private javax.swing.JTextField jTextFieldTextoMensagem;
    // End of variables declaration//GEN-END:variables
}
